{
 "title": "MD2K_DEMO",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "username",
    "query": "show tag values with key=\"owner_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Data Yield MSHRV-LED",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    {
     "alias": "MotionSenseHRV Left Wrist",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--LED--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "MotionSenseHRV Right Wrist",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--LED--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Yield MSHRV - Accel",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    {
     "alias": "MotionSenseHRV Left Wrist",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--LEFT_WRIST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "MotionSenseHRV Right Wrist",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--ACCELEROMETER--org.md2k.motionsense--MOTION_SENSE_HRV--RIGHT_WRIST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Yield AutoSenseBLE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    {
     "alias": "AutoSenseBLE Accelerometer",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--ACCELEROMETER--org.md2k.autosenseble--AUTOSENSE_BLE--CHEST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "AutoSenseBLE Respiration",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--RESPIRATION--org.md2k.autosenseble--AUTOSENSE_BLE--CHEST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "AutoSenseBLE ECG",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DATA_QUALITY_SUMMARY_MINUTE--ECG--org.md2k.autosenseble--AUTOSENSE_BLE--CHEST",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ 3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Geolocation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Geolocation (Work)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GEOFENCE_SUMMARY_MINUTE--Work--org.md2k.phonesensor--PHONE",
     "select": [
      [
       { "params": [ "Location-Name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "Geolocation (Home)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GEOFENCE_SUMMARY_MINUTE--Home--org.md2k.phonesensor--PHONE",
     "select": [
      [
       { "params": [ "Location-Name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Beacon Counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Beacon (Work)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BEACON--org.md2k.beacon--BEACON--WORK_1",
     "select": [
      [
       { "params": [ "RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "Beacon (Home)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BEACON--org.md2k.beacon--BEACON--HOME",
     "select": [
      [
       { "params": [ "RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Phone/SMS/Notifications",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of phone calls",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CU_CALL_TYPE--edu.dartmouth.eureka",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "Call-Type" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "Number of SMS messages",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CU_SMS_TYPE--edu.dartmouth.eureka",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "SMS-Type" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "Phone Notifications",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CU_NOTIF_POST_TICKERTEXT--edu.dartmouth.eureka",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Phone Screen Touches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Screen Touch Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "TOUCH_SCREEN--org.md2k.phonesensor--PHONE",
     "select": [
      [
       { "params": [ "value_0" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "Screen-Touch" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "owner_name", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  }
 ]
}